added business logic to project
dental-clinic-project/dental-clinic-client pull request #8
Opened 2024-10-26 15:59 UTC by kOnfie

2024-10-29 09:41 UTC, Sega-128 requested changes

2024-10-29 09:41 UTC, Sega-128 commented on src/app/store/services/services.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:8000/api/v1" }),
на бекенді поставили змінні середовища, а фронтенд обділили

http://localhost:8000/api/v1

2024-10-30 10:55 UTC, kOnfie commented on src/app/store/services/services.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: "http://localhost:8000/api/v1" }),
Я якраз це зробив, просто на dev. Добавлю сюди

2024-11-05 06:56 UTC, Sega-128 approved these changes

2024-11-05 20:17 UTC, merged